spring:
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
  application:
    name: yupao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: 030717ghs
    # session失效时间
  session:
    timeout: 86400


server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

  global-config:
    banner: off # 关闭mybatisplus启动图标
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1









